kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: pacman    
  name: pacman-route
spec:
  to:
    kind: Service
    name: pacman-svc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None